config/routes.rb
Rails.application.routes.draw do
  root "pets#index"

  
  resources :pets

  get "/signup" => "users#new"
  post "/users" => "users#create"

  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
  # Automatically generates the following routes
  # get "/pets" => "pets#index", as: "pets"
  # get "/pets/new" => "pets#new", as: "new_photo"
  # post "/pets" => "pets#create"
  # get "/pets/:id" => "pets#show", as: "photo"
  # get "/pets/:id/edit" => "pets#edit", as: "edit_photo"
  # patch "/pets/:id" => "pets#update"
  # delete "/pets/:id" => "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :breed, presence: true
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password
validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
 
  def authenticate_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
    render template: "pets/index"
  end
  def show
    @pet = Pet.find_by(id: params[:id])
    render template: "pets/show"
  end

  def new
    @pet = Pet.new
    render template: "pets/new"
  end
  def create
    @pet = Pet.new(
      name: params[:pet][:name],
      breed: params[:pet][:breed],
      image: params[:pet][:image]
    )
    if @pet.save
      redirect_to "/pets"
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @pet = Pet.find_by(id: params[:id])
    render template: "/pets/edit"
  end
  def update
    @pet = Pet.find_by(id: params[:id]) 
    @pet.name = params[:pet][:name]
    @pet.breed = params[:pet][:breed] 
    @pet.image = params[:pet][:image] 
    if @pet.save 
      redirect_to "/pets"
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @pet = Pet.find_by(id: params[:id])
    @pet.destroy
    redirect_to "/pets", status: :see_other
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end
 
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to "/login", status: :see_other unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<%= form_with model: @pet do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>
  <div>
    <%= form.submit %>
  </div>
  <%= link_to "Destroy pet", pet_path(@pet), data: {turbo_method: :delete} %>
<% end%>

app/views/pets/index.html.erb
    <ul class="nav ">
    <li class="nav-item flex-grow-1">
        <a class= "nav-link active" href="/pets">ALL THE PETS</a>
    </li>
    <li class="nav-item border border-2">
        <a class="nav-link active" aria-current="page" href="/pets/new">Add a pet</a>
    </li>
    <li class="nav-item border border-2">
        <a class="nav-link" href="/signup">Sign up</a>
    </li>
    <li class="nav-item border border-2">
        <a class="nav-link" href="/login">Login</a>
    </li>
    <li class="nav-item border border-2">
        <a class="nav-link disabled">Logout</a>
    </li>
    </ul>

<h1>All the pets</h1>

<% @pets.each do |pet| %>

    <h2><%= pet.name %></h2>
    <%= link_to "More Info", pet %>
<% end %>

app/views/pets/new.html.erb
<h1>New Pet</h1>
<%= form_with model: @pet do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @pet.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :breed %>
    <%= form.text_field :breed %>
    <% @pet.errors.full_messages_for(:breed).each do |message| %>
          <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.text_field :image %>
    <% @pet.errors.full_messages_for(:image).each do |message| %>
          <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end%>

app/views/pets/show.html.erb
<h1>pet info</h1>
<h2><%= @pet.name %></h2>
<p>Breed: <%= @pet.breed %></p>
<img src=<%= @pet.image%>>
<p><%= link_to "Edit pet", edit_pet_path(@pet) %></p>



<p><a href="/pets">Back to all pets</a></p>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>